#!/bin/bash

backtitle="WiFi configuration"
DHCPD_STARTUP_FILE=S80dhcp-server

# Store menu options selected by the user
INPUT=/tmp/menu.sh.$$

# trap and delete temp files
trap "rm $OUTPUT; rm $INPUT; exit" SIGHUP SIGINT SIGTERM

# Display a nice waiting dialog box
function retrieve_AP() {
  dialog --ok-label "Press enter now" \
    --prgbox "Reading network..." \
      "iwlist wlan0 scan > /tmp/AP" 6 30
}

function get_SSID() {
  # Only retrieve the SSID from iwlist output
  cat /tmp/AP | grep ESSID | awk -F':' '{ print $2 }' | cut -c 2- | sed s/.$//
}

function enter_ssid_and_pwd() {
  exec 3>&1
  value=$(dialog --title "Enter an SSID and password" --ok-label "Submit" \
    --backtitle "$backtitle" --insecure "$@" \
    --mixedform "Use the up/down arrow key to navigate the fields." 10 50 0 \
        "SSID"      1 1 "" 1 20 20 0 0 \
        "Password"  2 1 "" 2 20 20 0 1 \
    2>&1 1>&3)
  returncode=$?
  exec 3>&-

  IFS=$'\n' read -rd '' -a values <<<"$value"
  SSID=${values[0]}
  PWD=${values[1]}
  PSKEY=`wpa_passphrase $SSID $PWD | egrep "[^#]psk" | awk -F'=' '{ print $2 }'`
}

function enter_pwd_only() {
  exec 3>&1
  value=$(dialog --backtitle "$backtitle" \
    --title "Enter the AP password" --ok-label "Submit" --insecure \
    --mixedform "Use the up/down arrow key to navigate the fields." 10 50 0 \
      "SSID"      1 1 $1 1 20 20 0 2 \
      "Password"  2 1 "" 2 20 20 0 1 \
    2>&1 1>&3)
  returncode=$?
  exec 3>&-

  IFS=$'\n' read -rd '' -a values <<<"$value"
  SSID=${values[0]}
  PWD=${values[1]}
  PSKEY=`wpa_passphrase $SSID $PWD | egrep "[^#]psk" | awk -F'=' '{ print $2 }'`
}

function configure_client() {
  retrieve_AP
  LIST=`get_SSID`
  # Convert to radio box format
  LIST=`for x in $LIST; do echo -e $x \"\" off; done`
  # Chose you AP
  dialog --backtitle "$backtitle" \
    --radiolist "Choose an Access Point" 30 80 30 \
      "Manual" "Manuel Entry" off \
      $LIST 2> "${INPUT}"
  menuitem=$(<"${INPUT}")
  # Depending on your choice, enter the SSID and password or only the password
  case $menuitem in
    Manual) enter_ssid_and_pwd;;
    *) enter_pwd_only $menuitem;;
  esac

  if [[ $returncode -ne 0 ]]
  then
    nothing_done
  fi

  # Stop daemon
  /etc/init.d/hostapd stop
  /etc/init.d/$DHCPD_STARTUP_FILE stop

  # Rewrite configuration files
  sed 's/{{SSID}}/$SSID/g; s/{{PWD}}/$PWD/g; s/{{PSKEY}}/$PSKEY/g' \
    /etc/ezwifi/templates/etc/network/interface_client > /etc/network/interface
  sed 's/{{SSID}}/$SSID/g; s/{{PWD}}/$PWD/g; s/{{PSKEY}}/$PSKEY/g' \
    /etc/ezwifi/templates/etc/wpa_supplicant.conf > /etc/wpa_supplicant.conf
  # Disable dhcpd daemon
  mv /etc/init.d/$DHCPD_STARTUP_FILE /etc/init.d/_$DHCPD_STARTUP_FILE

  all_done
}

function configure_AP() {
  enter_ssid_and_pwd

  if [[ $returncode -ne 0 ]]
  then
    nothing_done
  fi

  # Rewrite configuration files
  sed 's/{{SSID}}/$SSID/g; s/{{PWD}}/$PWD/g; s/{{PSKEY}}/$PSKEY/g' \
    /etc/ezwifi/templates/etc/network/interface_AP > /etc/network/interface
  sed 's/{{SSID}}/$SSID/g; s/{{PWD}}/$PWD/g; s/{{PSKEY}}/$PSKEY/g' \
    /etc/ezwifi/templates/etc/hostapd/hostapd.conf > /etc/hostapd/hostapd.conf
  # Enable dhcpd daemon
  mv /etc/init.d/_$DHCPD_STARTUP_FILE /etc/init.d/$DHCPD_STARTUP_FILE

  # Stop daemon
  /etc/init.d/hostapd start
  /etc/init.d/$DHCPD_STARTUP_FILE start

  all_done
}

function all_done() {
  echo "Your configuration has been changed"
}

function nothing_done() {
  echo "Your configuration has not been modified"
  exit 1
}

dialog --backtitle "$backtitle" \
  --menu "Choose an option. /!\ Your previous network configuration will be permanently lost" 10 80 2 \
    "Client" "Configure as a simple client" \
    "AP" "Configure as an access point" 2>"${INPUT}"

menuitem=$(<"${INPUT}")

case $menuitem in
  Client) configure_client;;
  AP) configure_AP;;
  *) nothing_done;;
esac
