#!/bin/bash
#
# Will prompt for a SSID and password and modify the WiFi configuration file.
#

# Define some colors
NC='\[\033[0m\]' # No Color
RED='\[\033[0;31m\]'

FILE=/etc/hostapd/hostapd.conf

# Sanity check
if [[ ! -f $FILE ]]
then
  echo "Error: $FILE does not exist"
  exit 1
fi

# Prompt the user for SSID and password
SSID=
while [[ $SSID = "" ]]; do
  read -p "ssid: " SSID
done

# Check our replacement will work
grep 'ssid=' $FILE > /dev/null
if [[ $? -ne 0 ]]
then
  echo "${RED}Error:${NC} $FILE does not contain a ssid field"
  exit 1
fi
read -p "wifi password (won't be stored): " -s PASSWORD

# Check password staisfies wpa_passphrase requirement of at least 8 characters
if [[ `echo $PASSWORD | wc -c` -lt 8 ]]
then
  echo "${RED}Error:${NC} Password must contain at least 8 character"
  exit 1
fi

# Replace the SSID
sed -i "s/^ssid=.*/ssid=${SSID}/" $FILE

# Hash the password
KEY=`wpa_passphrase $SSID $PASSWORD | egrep "[^#]psk" | awk -F'=' '{ print $2 }'`

# Check our replacement will work
grep 'psk=' $FILE > /dev/null
if [[ $? -ne 0 ]]
then
  echo "${RED}Error:${NC} $FILE do not contain a psk field"
  exit 1
fi

# Replace the password
sed -ir s/^wpa_psk=.*/wpa_psk=$KEY/ $FILE

echo "AP configuration to SSID $SSID done"
