#!/bin/sh

check_configuration
if [[ $? -eq 0 ]]
then
  echo "Starting camera on $IFACE" > /dev/kmsg
	/etc/init.d/gst-launch $IFACE > /var/log/gst-launch 2>&1 &
else
  echo "Wifi not configured" > /dev/kmsg
fi

