#!/bin/sh
# This script installs the wpa hooks to be called when associating with
# an access point

case "$1" in
    start)
    if [ -x /usr/share/wpa/hooks.script ] ; then
      wpa_cli -a /usr/share/wpa/hooks.script -P /var/run/wpa_cli.pid 2>&1 > /dev/kmsg &
    fi
    ;;

    stop)
      kill -9 `cat /var/run/wpa_cli.pid`
    ;;

    *)
    echo "usage: $0 { start | stop }" >&2
    exit 1
    ;;
esac
