#!/bin/sh
# Start/stop the gst-launch service

case "$1" in
    start)
    if [ -x /usr/bin/gst-launch.sh ] ; then
      /usr/bin/gst-launch.sh &
    fi
    ;;

    stop)
    kill -9 $(cat /var/run/gst-launch.pid)
    ;;

    *)
    echo "usage: $0 { start | stop }" >&2
    exit 1
    ;;

esac

