#!/bin/sh

LOCKFILE=/var/run/skvs.lock

case "$1" in
  start)
    start-stop-daemon --start --chuid root --background --make-pidfile --pidfile $LOCKFILE --exec skvs -- --host 0.0.0.0 --storage $(mktemp -d)
    ;;

  stop)
    start-stop-daemon --stop --pidfile $LOCKFILE
    ;;

  *)
    echo "usage: $0 { start | stop }" >&2
    exit 1
  ;;
esac
