#!/bin/bash
#
# This script is launched everytime the wlan0 interface is started.
# It will check is a wifi network is configured and if it is not, will
# will execute configuration_wifi.sh.
#

FILE=/root/.wifi_configured

# Sanity check
if [[ ! -f $FILE ]]
then
  echo "WiFi needs to be configured" > /dev/kmsg
  exit 1
fi

# If the interface file contains {{SSID}}, it means we need to configure it
grep {{SSID}} $FILE > /dev/null
if [[ $? -eq 0 ]]
then
  echo "WiFi needs to be configured" > /dev/kmsg
  exit 1
fi

exit 0

